# Generated by Django 3.0.5 on 2020-05-16 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDCat', models.CharField(max_length=1200, unique=True)),
                ('Category', models.CharField(max_length=1200)),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDMD', models.CharField(max_length=1200, unique=True)),
                ('Domain', models.CharField(max_length=1200)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDM', models.CharField(max_length=1200, unique=True)),
                ('Domain', models.CharField(blank=True, max_length=1200)),
                ('Insight', models.CharField(blank=True, max_length=1200)),
                ('Query', models.CharField(blank=True, max_length=1200)),
                ('VQuery', models.CharField(blank=True, max_length=1200)),
                ('Recordcount', models.CharField(blank=True, max_length=1200)),
                ('LastRefreshedOn', models.DateTimeField(blank=True)),
                ('GraphValue', models.CharField(blank=True, max_length=1200)),
                ('Xaxis', models.CharField(blank=True, max_length=1200)),
                ('Yaxis', models.CharField(blank=True, max_length=1200)),
                ('Subtitle', models.CharField(blank=True, max_length=1200)),
                ('CategoryID', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='DetailsApp.Category')),
                ('DomainID', models.ForeignKey(default=5, on_delete=django.db.models.deletion.SET_DEFAULT, to='DetailsApp.Master')),
            ],
        ),
    ]
