# Generated by Django 3.0.5 on 2020-05-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DetailsApp', '0003_auto_20200518_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='LastRefreshedOn',
            field=models.DateTimeField(blank=True),
        ),
    ]
