# Generated by Django 3.0.5 on 2020-06-01 14:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DetailsApp', '0005_auto_20200527_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='LastRefreshedOn',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
